permalink: /:title

title: odouk.cn
Keyword: odouk.cn
Desc: odouk.cn

Path: doozz.github.io
Meta:
  Title: 一条咸鱼
  Subtitle: doozz.github.io

Nav:
 - Link: index
   Title: 归档
   Hover: index
 - Link: /
   Title: 文章
   Hover: archive
 - Link: about
   Title: 关于
   Hover: about

