permalink: /:title

title: odouk.cn
Keyword: odouk.cn
Desc: odouk.cn

Path: doozz.github.io
Meta:
  Title: 一条咸鱼
  Subtitle: doozz.github.io

Nav:
 - Link: /
   Title: 归档
   Hover: index
 - Link: /
   Title: 文章
   Hover: archive
# # set nav to active status
# hover = "archive"
# blank = false
